#!/bin/bash

sass-convert  .//_badge.scss  .//_badge.sass
sass-convert  .//_breadcrumb.scss .//_breadcrumb.sass
sass-convert  .//_button-group.scss .//_button-group.sass
sass-convert  .//_buttons.scss  .//_buttons.sass
sass-convert  .//_card.scss .//_card.sass
sass-convert  .//_carousel.scss .//_carousel.sass
sass-convert  .//_close.scss  .//_close.sass
sass-convert  .//_code.scss .//_code.sass
sass-convert  .//_custom-forms.scss .//_custom-forms.sass
sass-convert  .//_custom.scss .//_custom.sass
sass-convert  .//_dropdown.scss .//_dropdown.sass
sass-convert  .//_forms.scss  .//_forms.sass
sass-convert  .//_grid.scss .//_grid.sass
sass-convert  .//_images.scss .//_images.sass
sass-convert  .//_input-group.scss  .//_input-group.sass
sass-convert  .//_jumbotron.scss  .//_jumbotron.sass
sass-convert  .//_list-group.scss .//_list-group.sass
sass-convert  .//_media.scss  .//_media.sass
sass-convert  .//_mixins.scss .//_mixins.sass
sass-convert  .//_modal.scss  .//_modal.sass
sass-convert  .//_normalize.scss  .//_normalize.sass
sass-convert  .//_pagination.scss .//_pagination.sass
sass-convert  .//_popover.scss  .//_popover.sass
sass-convert  .//_print.scss  .//_print.sass
sass-convert  .//_progress.scss .//_progress.sass
sass-convert  .//_reboot.scss .//_reboot.sass
sass-convert  .//_responsive-embed.scss .//_responsive-embed.sass
sass-convert  .//_tables.scss .//_tables.sass
sass-convert  .//_tooltip.scss  .//_tooltip.sass
sass-convert  .//_transitions.scss  .//_transitions.sass
sass-convert  .//_type.scss .//_type.sass
sass-convert  .//_utilities.scss  .//_utilities.sass
sass-convert  .//mixins/_alert.scss .//mixins/_alert.sass
sass-convert  .//mixins/_background-variant.scss  .//mixins/_background-variant.sass
sass-convert  .//mixins/_badge.scss .//mixins/_badge.sass
sass-convert  .//mixins/_border-radius.scss .//mixins/_border-radius.sass
sass-convert  .//mixins/_breakpoints.scss .//mixins/_breakpoints.sass
sass-convert  .//mixins/_buttons.scss .//mixins/_buttons.sass
sass-convert  .//mixins/_cards.scss .//mixins/_cards.sass
sass-convert  .//mixins/_clearfix.scss  .//mixins/_clearfix.sass
sass-convert  .//mixins/_float.scss .//mixins/_float.sass
sass-convert  .//mixins/_forms.scss .//mixins/_forms.sass
sass-convert  .//mixins/_gradients.scss .//mixins/_gradients.sass
sass-convert  .//mixins/_grid-framework.scss  .//mixins/_grid-framework.sass
sass-convert  .//mixins/_grid.scss  .//mixins/_grid.sass
sass-convert  .//mixins/_hover.scss .//mixins/_hover.sass
sass-convert  .//mixins/_image.scss .//mixins/_image.sass
sass-convert  .//mixins/_list-group.scss  .//mixins/_list-group.sass
sass-convert  .//mixins/_lists.scss .//mixins/_lists.sass
sass-convert  .//mixins/_nav-divider.scss .//mixins/_nav-divider.sass
sass-convert  .//mixins/_navbar-align.scss  .//mixins/_navbar-align.sass
sass-convert  .//mixins/_pagination.scss  .//mixins/_pagination.sass
sass-convert  .//mixins/_reset-text.scss  .//mixins/_reset-text.sass
sass-convert  .//mixins/_resize.scss  .//mixins/_resize.sass
sass-convert  .//mixins/_screen-reader.scss .//mixins/_screen-reader.sass
sass-convert  .//mixins/_size.scss  .//mixins/_size.sass
sass-convert  .//mixins/_table-row.scss .//mixins/_table-row.sass
sass-convert  .//mixins/_text-emphasis.scss .//mixins/_text-emphasis.sass
sass-convert  .//mixins/_text-hide.scss .//mixins/_text-hide.sass
sass-convert  .//mixins/_text-truncate.scss .//mixins/_text-truncate.sass
sass-convert  .//mixins/_transforms.scss  .//mixins/_transforms.sass
sass-convert  .//mixins/_visibility.scss  .//mixins/_visibility.sass
sass-convert  .//utilities/_align.scss  .//utilities/_align.sass
sass-convert  .//utilities/_background.scss .//utilities/_background.sass
sass-convert  .//utilities/_borders.scss  .//utilities/_borders.sass
sass-convert  .//utilities/_clearfix.scss .//utilities/_clearfix.sass
sass-convert  .//utilities/_display.scss  .//utilities/_display.sass
sass-convert  .//utilities/_flex.scss .//utilities/_flex.sass
sass-convert  .//utilities/_float.scss  .//utilities/_float.sass
sass-convert  .//utilities/_position.scss .//utilities/_position.sass
sass-convert  .//utilities/_screenreaders.scss  .//utilities/_screenreaders.sass
sass-convert  .//utilities/_sizing.scss .//utilities/_sizing.sass
sass-convert  .//utilities/_spacing.scss  .//utilities/_spacing.sass
sass-convert  .//utilities/_text.scss .//utilities/_text.sass
sass-convert  .//utilities/_visibility.scss .//utilities/_visibility.sass
